Imports System
Imports System.Collections.Generic
Imports System.Text
Imports System.Drawing
Namespace System.Windows.Forms
	Public Class RibbonProfesionalRendererColorTable
		Public FormBorder As Color = FromHex("#3B5A82")
		Public OrbDropDownDarkBorder As Color = Color.FromArgb(&H9b, &Haf, &Hca)
		Public OrbDropDownLightBorder As Color = Color.FromArgb(&Hff, &Hff, &Hff)
		Public OrbDropDownBack As Color = Color.FromArgb(&Hbf, &Hd3, &Heb)
		Public OrbDropDownNorthA As Color = Color.FromArgb(&Hd7, &He5, &Hf7)
		Public OrbDropDownNorthB As Color = Color.FromArgb(&Hd4, &He1, &Hf3)
		Public OrbDropDownNorthC As Color = Color.FromArgb(&Hc6, &Hd8, &Hee)
		Public OrbDropDownNorthD As Color = Color.FromArgb(&Hb7, &Hca, &He6)
		Public OrbDropDownSouthC As Color = Color.FromArgb(&Hb0, &Hc9, &Hea)
		Public OrbDropDownSouthD As Color = Color.FromArgb(&Hcf, &He0, &Hf5)
		Public OrbDropDownContentbg As Color = Color.FromArgb(&He9, &Hea, &Hee)
		Public OrbDropDownContentbglight As Color = Color.FromArgb(&Hfa, &Hfa, &Hfa)
		Public OrbDropDownSeparatorlight As Color = Color.FromArgb(&Hf5, &Hf5, &Hf5)
		Public OrbDropDownSeparatordark As Color = Color.FromArgb(&Hc5, &Hc5, &Hc5)
		Public Caption1 As Color = FromHex("#E3EBF6")
		Public Caption2 As Color = FromHex("#DAE9FD")
		Public Caption3 As Color = FromHex("#D5E5FA")
		Public Caption4 As Color = FromHex("#D9E7F9")
		Public Caption5 As Color = FromHex("#CADEF7")
		Public Caption6 As Color = FromHex("#E4EFFD")
		Public Caption7 As Color = FromHex("#B0CFF7")
		Public QuickAccessBorderDark As Color = FromHex("#B6CAE2")
		Public QuickAccessBorderLight As Color = FromHex("#F2F6FB")
		Public QuickAccessUpper As Color = FromHex("#E0EBF9")
		Public QuickAccessLower As Color = FromHex("#C9D9EE")
		Public OrbOptionBorder As Color = FromHex("#7793B9")
		Public OrbOptionBackground As Color = FromHex("#E8F1FC")
		Public OrbOptionShine As Color = FromHex("#D2E1F4")
		Public Arrow As Color = FromHex("#678CBD")
		Public ArrowLight As Color = Color.FromArgb(200, Color.White)
		Public ArrowDisabled As Color = FromHex("#B7B7B7")
		Public Text As Color = FromHex("#15428B")
		Public OrbBackgroundDark As Color = FromHex("#7C8CA4")
		Public OrbBackgroundMedium As Color = FromHex("#99ABC6")
		Public OrbBackgroundLight As Color = Color.White
		Public OrbLight As Color = Color.White
		Public OrbSelectedBackgroundDark As Color = FromHex("#DFAA1A")
		Public OrbSelectedBackgroundMedium As Color = FromHex("#F9D12E")
		Public OrbSelectedBackgroundLight As Color = FromHex("#FFEF36")
		Public OrbSelectedLight As Color = FromHex("#FFF52B")
		Public OrbPressedBackgroundDark As Color = FromHex("#CE8410")
		Public OrbPressedBackgroundMedium As Color = FromHex("#CE8410")
		Public OrbPressedBackgroundLight As Color = FromHex("#F57603")
		Public OrbPressedLight As Color = FromHex("#F08500")
		Public OrbBorderAero As Color = FromHex("#99A1AD")
		Public RibbonBackground As Color = FromHex("#BFDBFF")
		Public TabBorder As Color = FromHex("#8DB2E3")
		Public TabNorth As Color = FromHex("#EBF3FE")
		Public TabSouth As Color = FromHex("#E1EAF6")
		Public TabGlow As Color = FromHex("#D1FBFF")
		Public TabText As Color = FromHex("#15428B")
		Public TabActiveText As Color = FromHex("#15428B")
		Public TabContentNorth As Color = FromHex("#C8D9ED")
		Public TabContentSouth As Color = FromHex("#E7F2FF")
		Public TabSelectedGlow As Color = FromHex("#E1D2A5")
		Public PanelDarkBorder As Color = Color.FromArgb(51, FromHex("#15428B"))
		Public PanelLightBorder As Color = Color.FromArgb(102, Color.White)
		Public PanelTextBackground As Color = FromHex("#C2D9F0")
		Public PanelTextBackgroundSelected As Color = FromHex("#C2D9F0")
		Public PanelText As Color = FromHex("#15428B")
		Public PanelBackgroundSelected As Color = Color.FromArgb(102, FromHex("#E8FFFD"))
		Public PanelOverflowBackground As Color = FromHex("#B9D1F0")
		Public PanelOverflowBackgroundPressed As Color = FromHex("#7699C8")
		Public PanelOverflowBackgroundSelectedNorth As Color = Color.FromArgb(100, Color.White)
		Public PanelOverflowBackgroundSelectedSouth As Color = Color.FromArgb(102, FromHex("#B8D7FD"))
		Public ButtonBgOut As Color = FromHex("#C1D5F1")
		Public ButtonBgCenter As Color = FromHex("#CFE0F7")
		Public ButtonBorderOut As Color = FromHex("#B9D0ED")
		Public ButtonBorderIn As Color = FromHex("#E3EDFB")
		Public ButtonGlossyNorth As Color = FromHex("#DEEBFE")
		Public ButtonGlossySouth As Color = FromHex("#CBDEF6")
		Public ButtonDisabledBgOut As Color = FromHex("#E0E4E8")
		Public ButtonDisabledBgCenter As Color = FromHex("#E8EBEF")
		Public ButtonDisabledBorderOut As Color = FromHex("#C5D1DE")
		Public ButtonDisabledBorderIn As Color = FromHex("#F1F3F5")
		Public ButtonDisabledGlossyNorth As Color = FromHex("#F0F3F6")
		Public ButtonDisabledGlossySouth As Color = FromHex("#EAEDF1")
		Public ButtonSelectedBgOut As Color = FromHex("#FFD646")
		Public ButtonSelectedBgCenter As Color = FromHex("#FFEAAC")
		Public ButtonSelectedBorderOut As Color = FromHex("#C2A978")
		Public ButtonSelectedBorderIn As Color = FromHex("#FFF2C7")
		Public ButtonSelectedGlossyNorth As Color = FromHex("#FFFDDB")
		Public ButtonSelectedGlossySouth As Color = FromHex("#FFE793")
		Public ButtonPressedBgOut As Color = FromHex("#F88F2C")
		Public ButtonPressedBgCenter As Color = FromHex("#FDF1B0")
		Public ButtonPressedBorderOut As Color = FromHex("#8E8165")
		Public ButtonPressedBorderIn As Color = FromHex("#F9C65A")
		Public ButtonPressedGlossyNorth As Color = FromHex("#FDD5A8")
		Public ButtonPressedGlossySouth As Color = FromHex("#FBB062")
		Public ButtonCheckedBgOut As Color = FromHex("#F9AA45")
		Public ButtonCheckedBgCenter As Color = FromHex("#FDEA9D")
		Public ButtonCheckedBorderOut As Color = FromHex("#8E8165")
		Public ButtonCheckedBorderIn As Color = FromHex("#F9C65A")
		Public ButtonCheckedGlossyNorth As Color = FromHex("#F8DBB7")
		Public ButtonCheckedGlossySouth As Color = FromHex("#FED18E")
		Public ItemGroupOuterBorder As Color = FromHex("#9EBAE1")
		Public ItemGroupInnerBorder As Color = Color.FromArgb(51, Color.White)
		Public ItemGroupSeparatorLight As Color = Color.FromArgb(64, Color.White)
		Public ItemGroupSeparatorDark As Color = Color.FromArgb(38, FromHex("#9EBAE1"))
		Public ItemGroupBgNorth As Color = FromHex("#CADCF0")
		Public ItemGroupBgSouth As Color = FromHex("#D0E1F7")
		Public ItemGroupBgGlossy As Color = FromHex("#BCD0E9")
		Public ButtonListBorder As Color = FromHex("#B9D0ED")
		Public ButtonListBg As Color = FromHex("#D4E6F8")
		Public ButtonListBgSelected As Color = FromHex("#ECF3FB")
		Public DropDownBg As Color = FromHex("#FAFAFA")
		Public DropDownImageBg As Color = FromHex("#E9EEEE")
		Public DropDownImageSeparator As Color = FromHex("#C5C5C5")
		Public DropDownBorder As Color = FromHex("#868686")
		Public DropDownGripNorth As Color = FromHex("#FFFFFF")
		Public DropDownGripSouth As Color = FromHex("#DFE9EF")
		Public DropDownGripBorder As Color = FromHex("#DDE7EE")
		Public DropDownGripDark As Color = FromHex("#5574A7")
		Public DropDownGripLight As Color = FromHex("#FFFFFF")
		Public SeparatorLight As Color = FromHex("#FAFBFD")
		Public SeparatorDark As Color = FromHex("#96B4DA")
		Public SeparatorBg As Color = FromHex("#DAE6EE")
		Public SeparatorLine As Color = FromHex("#C5C5C5")
		Public TextBoxUnselectedBg As Color = FromHex("#EAF2FB")
		Public TextBoxBorder As Color = FromHex("#ABC1DE")
		Friend Shared Function FromHex(hex As String) As Color
			If hex.StartsWith("#") Then
				hex = hex.Substring(1)
			End If
			If hex.Length <> 6 Then
				Throw New Exception("Color not valid")
			End If
			Return Color.FromArgb(Integer.Parse(hex.Substring(0, 2), System.Globalization.NumberStyles.HexNumber), Integer.Parse(hex.Substring(2, 2), System.Globalization.NumberStyles.HexNumber), Integer.Parse(hex.Substring(4, 2), System.Globalization.NumberStyles.HexNumber))
		End Function
		Friend Shared Function ToGray(c As Color) As Color
			Dim m As Integer = (c.R + c.G + c.B) / 3
			Return Color.FromArgb(m, m, m)
		End Function
	End Class
End Namespace
